FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS base
WORKDIR /app
EXPOSE 80
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /src
COPY ["HelloWorldApp.Web/HelloWorldApp.Web.csproj", "HelloWorldApp.Web/"]
RUN dotnet restore "HelloWorldApp.Web/HelloWorldApp.Web.csproj"
COPY . .
WORKDIR "/src/HelloWorldApp.Web"
RUN dotnet build "HelloWorldApp.Web.csproj" -c Release -o /app/build
FROM build AS publish
RUN dotnet publish "HelloWorldApp.Web.csproj" -c Release -o /app/publish
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "HelloWorldApp.Web.dll"]
